#!/usr/bin/env node
// Packs the server as a Claude Desktop extension (.mcpb) so it gets an on/off
// switch in the app UI instead of living silently in claude_desktop_config.json.
//
//   node scripts/bundle.ts
//
// The bundle is a thin launcher: it does NOT copy the server, it points at this
// working copy, so edits take effect on the next app restart with no repack.
// The tool list in the manifest is read from the live server so it can't drift.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BUILD_DIR = path.join(ROOT, "mcpb");
const OUT_FILE = path.join(ROOT, "telegram.mcpb");
const ENTRY = path.join(ROOT, "bin", "telegram-mcp.ts");
// Claude Desktop resolves bare commands against the real login-shell PATH
// (its logs show `npx` resolving into ~/.nvm/...), so a bare `node` follows
// whatever nvm currently points at and survives Node upgrades. Set
// TELEGRAM_MCP_NODE to pin a specific binary instead.
const NODE_BIN = process.env.TELEGRAM_MCP_NODE || "node";
const MIN_NODE = "22.18";

// Icon variants copied into the bundle root; missing files are skipped so the
// build still works on a checkout without assets/.
const ICONS = [
  { file: "icon-128.png", size: "128x128" },
  { file: "icon-16.png", size: "16x16" },
].filter(({ file }) => fs.existsSync(path.join(ROOT, "assets", file)));

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
  version: string;
  description: string;
  author?: string | { name?: string };
};

// The manifest requires an author name; take it from package.json so the
// bundle carries whoever owns this checkout, not a hardcoded person.
const authorName =
  (typeof pkg.author === "string" ? pkg.author : pkg.author?.name) || "telegram-mcp";

async function readTools(): Promise<{ name: string; description: string }[]> {
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [ENTRY],
    cwd: ROOT,
    stderr: "pipe",
  });
  const client = new Client({ name: "bundle", version: "1.0.0" });
  await client.connect(transport);
  const { tools } = await client.listTools();
  await client.close();
  return tools.map((t) => ({
    name: t.name,
    description: (t.description ?? "").split(". ")[0] ?? "",
  }));
}

const tools = await readTools();

const manifest = {
  manifest_version: "0.3",
  name: "telegram",
  display_name: "Telegram",
  version: pkg.version,
  description: pkg.description,
  author: { name: authorName },
  ...(ICONS[0] ? { icon: ICONS[0].file } : {}),
  ...(ICONS.length ? { icons: ICONS.map(({ file, size }) => ({ src: file, size })) } : {}),
  server: {
    type: "node",
    entry_point: "server/index.mjs",
    mcp_config: {
      command: NODE_BIN,
      args: ["${__dirname}/server/index.mjs"],
      env: {
        TELEGRAM_MCP_READ_ONLY: "${user_config.read_only}",
        TELEGRAM_MCP_TZ: "${user_config.timezone}",
      },
    },
  },
  user_config: {
    read_only: {
      type: "boolean",
      title: "Read-only mode",
      description: "Register only the reading tools — no sending, editing, deleting or voting.",
      default: false,
    },
    timezone: {
      type: "string",
      title: "Timezone",
      description: "Timezone for rendered message timestamps, e.g. Europe/Moscow. Empty = system default.",
      default: "",
      required: false,
    },
  },
  tools,
};

// The launcher lives inside the bundle and forwards to the working copy.
// It must be .mjs: once installed there is no package.json next to it, so a
// plain .js would be parsed as CommonJS and `import` would blow up.
const launcher = `#!/usr/bin/env node
// Generated by scripts/bundle.ts — do not edit.
// Thin launcher: runs the Telegram MCP server from its working copy.
const [major, minor] = process.versions.node.split(".").map(Number);
if (major < 22 || (major === 22 && minor < 18)) {
  console.error(
    "telegram-mcp needs Node >= ${MIN_NODE} to run TypeScript directly, but this is " +
      process.versions.node +
      ". Upgrade Node, or repack with TELEGRAM_MCP_NODE=/path/to/node npm run bundle."
  );
  process.exit(1);
}
await import(${JSON.stringify(ENTRY)});
`;

fs.rmSync(BUILD_DIR, { recursive: true, force: true });
fs.mkdirSync(path.join(BUILD_DIR, "server"), { recursive: true });
fs.writeFileSync(path.join(BUILD_DIR, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
fs.writeFileSync(path.join(BUILD_DIR, "server", "index.mjs"), launcher);
for (const { file } of ICONS) {
  fs.copyFileSync(path.join(ROOT, "assets", file), path.join(BUILD_DIR, file));
}

fs.rmSync(OUT_FILE, { force: true });
execFileSync("zip", ["-r", "-q", OUT_FILE, "manifest.json", "server", ...ICONS.map((i) => i.file)], {
  cwd: BUILD_DIR,
});

console.log(`Built ${OUT_FILE}`);
console.log(`  node:   ${NODE_BIN}${NODE_BIN === "node" ? " (resolved from PATH at launch)" : ""}`);
console.log(`  server: ${ENTRY}`);
console.log(`  tools:  ${tools.length}`);
console.log(`  icons:  ${ICONS.map((i) => i.size).join(", ") || "(none)"}`);
console.log("\nInstall: Claude Desktop → Settings → Extensions → Advanced settings →");
console.log("Extension Developer → Install extension… and pick the file above.");
